### PR TITLE
Feat anscestor attributes

### PR DESCRIPTION
**Pull request by ephetic**
## Description

Updates use of @medv/finder to include `[data-qa="xxx"]` attributes throughout selector, not just on the clicked element.  This maximizes the value of the custom attribute setting.  See issue #52.

## Type of change

Please delete options that are not relevant.

- [√] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

A test has been created that shows clicking on a descendent `span` records a selector like

```
'body > #content-root > [data-qa="article-wrapper"] > [data-qa="article-body"] > span'
```

Existing tests unaffected.

## Checklist:

- [√] My code follows the style guidelines of this project. `npm run lint` passes with no errors.
- [x] I have made corresponding changes to the documentation
- [√] I have added tests that prove my fix is effective or that my feature works
- [√] New and existing unit tests pass locally with my changes. `npm run test` passes with no errors.

### CODE REVIEW

**Comment by ephetic** [comment]
Seeing test flakiness.  Hold off on this for now.

**Comment by ephetic** [comment]
Okay, it looks like running the jest tests in parallel upsets the express server (EADDRINUSE) such that the race causes one or both (?) servers to fail, failing those tests.  This is how I've fixed it locally (with commensurate changes to the test files that call this helper)

```
export const startServer = function (buildDir, file) {
  return new Promise((resolve, reject) => {
    const app = express()
    app.use('/build', express.static(path.join(__dirname, buildDir)))
    app.get('/', (req, res) => {
      res.status(200).sendFile(file, { root: __dirname })
    })
    let server
    let port
    const retry = (e) => {
      if(e.code == 'EADDRINUSE') {
        setTimeout(() => connect, 1000)
      }
    }
    const connect = () => {
      port = 0|(Math.random() * 1000) + 3000
      server = app.listen(port)
      server.once('error', retry)
      server.once('listening', () => {
        return resolve({server, port})
      })
    }
    connect()
  })
}
```

**Comment by tnolet** [comment]
Hey @ephetic this looks great, I'll have time to look at it earliest somewhere next week. Sorry for the delay.

**Comment by tnolet** [comment]
@ephetic LGTM I'm merging it and will push a point release.

**Pull request merged**
